// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package db

import (
	"context"
	"encoding/json"
)

const createArtifact = `-- name: CreateArtifact :one
insert into artifacts (
    artifact_id,
    tenant_id,
    task_id,
    user_id,
    type,
    name,
    media_type,
    storage_backend,
    storage_key,
    content_json,
    size_bytes,
    checksum_sha256,
    metadata,
    status
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
returning artifact_id, tenant_id, task_id, user_id, type, name, media_type, storage_backend, storage_key, content_json, size_bytes, checksum_sha256, metadata, status, created_at, updated_at
`

type CreateArtifactParams struct {
	ArtifactID     string          `db:"artifact_id" json:"artifact_id"`
	TenantID       string          `db:"tenant_id" json:"tenant_id"`
	TaskID         string          `db:"task_id" json:"task_id"`
	UserID         string          `db:"user_id" json:"user_id"`
	Type           ArtifactType    `db:"type" json:"type"`
	Name           string          `db:"name" json:"name"`
	MediaType      *string         `db:"media_type" json:"media_type"`
	StorageBackend string          `db:"storage_backend" json:"storage_backend"`
	StorageKey     *string         `db:"storage_key" json:"storage_key"`
	ContentJson    json.RawMessage `db:"content_json" json:"content_json"`
	SizeBytes      int64           `db:"size_bytes" json:"size_bytes"`
	ChecksumSha256 *string         `db:"checksum_sha256" json:"checksum_sha256"`
	Metadata       json.RawMessage `db:"metadata" json:"metadata"`
	Status         ArtifactStatus  `db:"status" json:"status"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ArtifactID,
		arg.TenantID,
		arg.TaskID,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.MediaType,
		arg.StorageBackend,
		arg.StorageKey,
		arg.ContentJson,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.Metadata,
		arg.Status,
	)
	var i Artifact
	err := row.Scan(
		&i.ArtifactID,
		&i.TenantID,
		&i.TaskID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.MediaType,
		&i.StorageBackend,
		&i.StorageKey,
		&i.ContentJson,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Metadata,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
select artifact_id, tenant_id, task_id, user_id, type, name, media_type, storage_backend, storage_key, content_json, size_bytes, checksum_sha256, metadata, status, created_at, updated_at
from artifacts
where tenant_id = $1
  and artifact_id = $2
limit 1
`

type GetArtifactParams struct {
	TenantID   string `db:"tenant_id" json:"tenant_id"`
	ArtifactID string `db:"artifact_id" json:"artifact_id"`
}

func (q *Queries) GetArtifact(ctx context.Context, arg GetArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, arg.TenantID, arg.ArtifactID)
	var i Artifact
	err := row.Scan(
		&i.ArtifactID,
		&i.TenantID,
		&i.TaskID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.MediaType,
		&i.StorageBackend,
		&i.StorageKey,
		&i.ContentJson,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Metadata,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtifactsByTask = `-- name: ListArtifactsByTask :many
select artifact_id, tenant_id, task_id, user_id, type, name, media_type, storage_backend, storage_key, content_json, size_bytes, checksum_sha256, metadata, status, created_at, updated_at
from artifacts
where tenant_id = $1
  and task_id = $2
  and status = 'AVAILABLE'
order by created_at desc, artifact_id desc
limit $4
offset $3
`

type ListArtifactsByTaskParams struct {
	TenantID   string `db:"tenant_id" json:"tenant_id"`
	TaskID     string `db:"task_id" json:"task_id"`
	OffsetRows int32  `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32  `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListArtifactsByTask(ctx context.Context, arg ListArtifactsByTaskParams) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByTask,
		arg.TenantID,
		arg.TaskID,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ArtifactID,
			&i.TenantID,
			&i.TaskID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.MediaType,
			&i.StorageBackend,
			&i.StorageKey,
			&i.ContentJson,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.Metadata,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArtifactDeleted = `-- name: MarkArtifactDeleted :one
update artifacts
set status = 'DELETED',
    updated_at = now()
where tenant_id = $1
  and artifact_id = $2
returning artifact_id, tenant_id, task_id, user_id, type, name, media_type, storage_backend, storage_key, content_json, size_bytes, checksum_sha256, metadata, status, created_at, updated_at
`

type MarkArtifactDeletedParams struct {
	TenantID   string `db:"tenant_id" json:"tenant_id"`
	ArtifactID string `db:"artifact_id" json:"artifact_id"`
}

func (q *Queries) MarkArtifactDeleted(ctx context.Context, arg MarkArtifactDeletedParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, markArtifactDeleted, arg.TenantID, arg.ArtifactID)
	var i Artifact
	err := row.Scan(
		&i.ArtifactID,
		&i.TenantID,
		&i.TaskID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.MediaType,
		&i.StorageBackend,
		&i.StorageKey,
		&i.ContentJson,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Metadata,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
