// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package db

import (
	"context"
	"encoding/json"
)

const createAuditLog = `-- name: CreateAuditLog :one
insert into audit_logs (
    audit_id,
    actor_id,
    tenant_id,
    action,
    resource_type,
    resource_id,
    before,
    after,
    ip,
    user_agent
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
returning audit_id, actor_id, tenant_id, action, resource_type, resource_id, before, after, ip, user_agent, created_at
`

type CreateAuditLogParams struct {
	AuditID      string          `db:"audit_id" json:"audit_id"`
	ActorID      string          `db:"actor_id" json:"actor_id"`
	TenantID     *string         `db:"tenant_id" json:"tenant_id"`
	Action       string          `db:"action" json:"action"`
	ResourceType string          `db:"resource_type" json:"resource_type"`
	ResourceID   *string         `db:"resource_id" json:"resource_id"`
	Before       json.RawMessage `db:"before" json:"before"`
	After        json.RawMessage `db:"after" json:"after"`
	Ip           *string         `db:"ip" json:"ip"`
	UserAgent    *string         `db:"user_agent" json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.AuditID,
		arg.ActorID,
		arg.TenantID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Before,
		arg.After,
		arg.Ip,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.AuditID,
		&i.ActorID,
		&i.TenantID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Before,
		&i.After,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLog = `-- name: GetAuditLog :one
select audit_id, actor_id, tenant_id, action, resource_type, resource_id, before, after, ip, user_agent, created_at
from audit_logs
where audit_id = $1
limit 1
`

func (q *Queries) GetAuditLog(ctx context.Context, auditID string) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLog, auditID)
	var i AuditLog
	err := row.Scan(
		&i.AuditID,
		&i.ActorID,
		&i.TenantID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Before,
		&i.After,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}
