// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkpoints.sql

package db

import (
	"context"
	"encoding/json"
)

const createCheckpoint = `-- name: CreateCheckpoint :one
insert into checkpoints (
    checkpoint_id,
    tenant_id,
    task_id,
    state_version,
    event_offset,
    state_snapshot,
    reason,
    trace_id
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
returning checkpoint_id, task_id, tenant_id, state_version, event_offset, state_snapshot, reason, trace_id, created_at
`

type CreateCheckpointParams struct {
	CheckpointID  string          `db:"checkpoint_id" json:"checkpoint_id"`
	TenantID      string          `db:"tenant_id" json:"tenant_id"`
	TaskID        string          `db:"task_id" json:"task_id"`
	StateVersion  int32           `db:"state_version" json:"state_version"`
	EventOffset   int64           `db:"event_offset" json:"event_offset"`
	StateSnapshot json.RawMessage `db:"state_snapshot" json:"state_snapshot"`
	Reason        string          `db:"reason" json:"reason"`
	TraceID       *string         `db:"trace_id" json:"trace_id"`
}

func (q *Queries) CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) (Checkpoint, error) {
	row := q.db.QueryRow(ctx, createCheckpoint,
		arg.CheckpointID,
		arg.TenantID,
		arg.TaskID,
		arg.StateVersion,
		arg.EventOffset,
		arg.StateSnapshot,
		arg.Reason,
		arg.TraceID,
	)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.TaskID,
		&i.TenantID,
		&i.StateVersion,
		&i.EventOffset,
		&i.StateSnapshot,
		&i.Reason,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const getCheckpoint = `-- name: GetCheckpoint :one
select checkpoint_id, task_id, tenant_id, state_version, event_offset, state_snapshot, reason, trace_id, created_at
from checkpoints
where tenant_id = $1
  and checkpoint_id = $2
limit 1
`

type GetCheckpointParams struct {
	TenantID     string `db:"tenant_id" json:"tenant_id"`
	CheckpointID string `db:"checkpoint_id" json:"checkpoint_id"`
}

func (q *Queries) GetCheckpoint(ctx context.Context, arg GetCheckpointParams) (Checkpoint, error) {
	row := q.db.QueryRow(ctx, getCheckpoint, arg.TenantID, arg.CheckpointID)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.TaskID,
		&i.TenantID,
		&i.StateVersion,
		&i.EventOffset,
		&i.StateSnapshot,
		&i.Reason,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestCheckpoint = `-- name: GetLatestCheckpoint :one
select checkpoint_id, task_id, tenant_id, state_version, event_offset, state_snapshot, reason, trace_id, created_at
from checkpoints
where tenant_id = $1
  and task_id = $2
order by created_at desc, checkpoint_id desc
limit 1
`

type GetLatestCheckpointParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	TaskID   string `db:"task_id" json:"task_id"`
}

func (q *Queries) GetLatestCheckpoint(ctx context.Context, arg GetLatestCheckpointParams) (Checkpoint, error) {
	row := q.db.QueryRow(ctx, getLatestCheckpoint, arg.TenantID, arg.TaskID)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.TaskID,
		&i.TenantID,
		&i.StateVersion,
		&i.EventOffset,
		&i.StateSnapshot,
		&i.Reason,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestCheckpointByReason = `-- name: GetLatestCheckpointByReason :one
select checkpoint_id, task_id, tenant_id, state_version, event_offset, state_snapshot, reason, trace_id, created_at
from checkpoints
where tenant_id = $1
  and task_id = $2
  and reason = $3
order by created_at desc, checkpoint_id desc
limit 1
`

type GetLatestCheckpointByReasonParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	TaskID   string `db:"task_id" json:"task_id"`
	Reason   string `db:"reason" json:"reason"`
}

func (q *Queries) GetLatestCheckpointByReason(ctx context.Context, arg GetLatestCheckpointByReasonParams) (Checkpoint, error) {
	row := q.db.QueryRow(ctx, getLatestCheckpointByReason, arg.TenantID, arg.TaskID, arg.Reason)
	var i Checkpoint
	err := row.Scan(
		&i.CheckpointID,
		&i.TaskID,
		&i.TenantID,
		&i.StateVersion,
		&i.EventOffset,
		&i.StateSnapshot,
		&i.Reason,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const listCheckpointsByTask = `-- name: ListCheckpointsByTask :many
select checkpoint_id, task_id, tenant_id, state_version, event_offset, state_snapshot, reason, trace_id, created_at
from checkpoints
where tenant_id = $1
  and task_id = $2
order by created_at desc, checkpoint_id desc
limit $4
offset $3
`

type ListCheckpointsByTaskParams struct {
	TenantID   string `db:"tenant_id" json:"tenant_id"`
	TaskID     string `db:"task_id" json:"task_id"`
	OffsetRows int32  `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32  `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListCheckpointsByTask(ctx context.Context, arg ListCheckpointsByTaskParams) ([]Checkpoint, error) {
	rows, err := q.db.Query(ctx, listCheckpointsByTask,
		arg.TenantID,
		arg.TaskID,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkpoint{}
	for rows.Next() {
		var i Checkpoint
		if err := rows.Scan(
			&i.CheckpointID,
			&i.TaskID,
			&i.TenantID,
			&i.StateVersion,
			&i.EventOffset,
			&i.StateSnapshot,
			&i.Reason,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneCheckpoints = `-- name: PruneCheckpoints :exec
delete from checkpoints
where checkpoints.tenant_id = $1
  and checkpoints.task_id = $2
  and checkpoints.checkpoint_id not in (
      select recent.checkpoint_id
      from checkpoints as recent
      where recent.tenant_id = $1
        and recent.task_id = $2
      order by recent.created_at desc, recent.checkpoint_id desc
      limit $3
  )
`

type PruneCheckpointsParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	TaskID   string `db:"task_id" json:"task_id"`
	KeepRows int32  `db:"keep_rows" json:"keep_rows"`
}

func (q *Queries) PruneCheckpoints(ctx context.Context, arg PruneCheckpointsParams) error {
	_, err := q.db.Exec(ctx, pruneCheckpoints, arg.TenantID, arg.TaskID, arg.KeepRows)
	return err
}
