// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"encoding/json"
)

const createAgentEvent = `-- name: CreateAgentEvent :one
insert into agent_events (
    tenant_id,
    task_id,
    type,
    input,
    output,
    metadata,
    trace_id,
    span_id
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
returning event_id, task_id, tenant_id, type, input, output, metadata, trace_id, span_id, created_at
`

type CreateAgentEventParams struct {
	TenantID string          `db:"tenant_id" json:"tenant_id"`
	TaskID   string          `db:"task_id" json:"task_id"`
	Type     string          `db:"type" json:"type"`
	Input    json.RawMessage `db:"input" json:"input"`
	Output   json.RawMessage `db:"output" json:"output"`
	Metadata json.RawMessage `db:"metadata" json:"metadata"`
	TraceID  *string         `db:"trace_id" json:"trace_id"`
	SpanID   *string         `db:"span_id" json:"span_id"`
}

func (q *Queries) CreateAgentEvent(ctx context.Context, arg CreateAgentEventParams) (AgentEvent, error) {
	row := q.db.QueryRow(ctx, createAgentEvent,
		arg.TenantID,
		arg.TaskID,
		arg.Type,
		arg.Input,
		arg.Output,
		arg.Metadata,
		arg.TraceID,
		arg.SpanID,
	)
	var i AgentEvent
	err := row.Scan(
		&i.EventID,
		&i.TaskID,
		&i.TenantID,
		&i.Type,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.TraceID,
		&i.SpanID,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentEvent = `-- name: GetAgentEvent :one
select event_id, task_id, tenant_id, type, input, output, metadata, trace_id, span_id, created_at
from agent_events
where tenant_id = $1
  and task_id = $2
  and event_id = $3
limit 1
`

type GetAgentEventParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	TaskID   string `db:"task_id" json:"task_id"`
	EventID  int64  `db:"event_id" json:"event_id"`
}

func (q *Queries) GetAgentEvent(ctx context.Context, arg GetAgentEventParams) (AgentEvent, error) {
	row := q.db.QueryRow(ctx, getAgentEvent, arg.TenantID, arg.TaskID, arg.EventID)
	var i AgentEvent
	err := row.Scan(
		&i.EventID,
		&i.TaskID,
		&i.TenantID,
		&i.Type,
		&i.Input,
		&i.Output,
		&i.Metadata,
		&i.TraceID,
		&i.SpanID,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentEventsByTask = `-- name: ListAgentEventsByTask :many
select event_id, task_id, tenant_id, type, input, output, metadata, trace_id, span_id, created_at
from agent_events
where tenant_id = $1
  and task_id = $2
  and event_id > $3
order by event_id asc
limit $4
`

type ListAgentEventsByTaskParams struct {
	TenantID     string `db:"tenant_id" json:"tenant_id"`
	TaskID       string `db:"task_id" json:"task_id"`
	AfterEventID int64  `db:"after_event_id" json:"after_event_id"`
	LimitRows    int32  `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListAgentEventsByTask(ctx context.Context, arg ListAgentEventsByTaskParams) ([]AgentEvent, error) {
	rows, err := q.db.Query(ctx, listAgentEventsByTask,
		arg.TenantID,
		arg.TaskID,
		arg.AfterEventID,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEvent{}
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.EventID,
			&i.TaskID,
			&i.TenantID,
			&i.Type,
			&i.Input,
			&i.Output,
			&i.Metadata,
			&i.TraceID,
			&i.SpanID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentEventsByType = `-- name: ListAgentEventsByType :many
select event_id, task_id, tenant_id, type, input, output, metadata, trace_id, span_id, created_at
from agent_events
where tenant_id = $1
  and type = $2
order by created_at desc, event_id desc
limit $4
offset $3
`

type ListAgentEventsByTypeParams struct {
	TenantID   string `db:"tenant_id" json:"tenant_id"`
	Type       string `db:"type" json:"type"`
	OffsetRows int32  `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32  `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListAgentEventsByType(ctx context.Context, arg ListAgentEventsByTypeParams) ([]AgentEvent, error) {
	rows, err := q.db.Query(ctx, listAgentEventsByType,
		arg.TenantID,
		arg.Type,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEvent{}
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.EventID,
			&i.TaskID,
			&i.TenantID,
			&i.Type,
			&i.Input,
			&i.Output,
			&i.Metadata,
			&i.TraceID,
			&i.SpanID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
