// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApprovalStatus string

const (
	ApprovalStatusPENDING  ApprovalStatus = "PENDING"
	ApprovalStatusAPPROVED ApprovalStatus = "APPROVED"
	ApprovalStatusREJECTED ApprovalStatus = "REJECTED"
	ApprovalStatusEXPIRED  ApprovalStatus = "EXPIRED"
	ApprovalStatusCANCELED ApprovalStatus = "CANCELED"
)

func (e *ApprovalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApprovalStatus(s)
	case string:
		*e = ApprovalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApprovalStatus: %T", src)
	}
	return nil
}

type NullApprovalStatus struct {
	ApprovalStatus ApprovalStatus `json:"approval_status"`
	Valid          bool           `json:"valid"` // Valid is true if ApprovalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApprovalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApprovalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApprovalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApprovalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApprovalStatus), nil
}

type ArtifactStatus string

const (
	ArtifactStatusAVAILABLE ArtifactStatus = "AVAILABLE"
	ArtifactStatusDELETED   ArtifactStatus = "DELETED"
)

func (e *ArtifactStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtifactStatus(s)
	case string:
		*e = ArtifactStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtifactStatus: %T", src)
	}
	return nil
}

type NullArtifactStatus struct {
	ArtifactStatus ArtifactStatus `json:"artifact_status"`
	Valid          bool           `json:"valid"` // Valid is true if ArtifactStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtifactStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ArtifactStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtifactStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtifactStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtifactStatus), nil
}

type ArtifactType string

const (
	ArtifactTypeTEXT   ArtifactType = "TEXT"
	ArtifactTypeJSON   ArtifactType = "JSON"
	ArtifactTypeFILE   ArtifactType = "FILE"
	ArtifactTypeIMAGE  ArtifactType = "IMAGE"
	ArtifactTypeREPORT ArtifactType = "REPORT"
	ArtifactTypeOTHER  ArtifactType = "OTHER"
)

func (e *ArtifactType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtifactType(s)
	case string:
		*e = ArtifactType(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtifactType: %T", src)
	}
	return nil
}

type NullArtifactType struct {
	ArtifactType ArtifactType `json:"artifact_type"`
	Valid        bool         `json:"valid"` // Valid is true if ArtifactType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtifactType) Scan(value interface{}) error {
	if value == nil {
		ns.ArtifactType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtifactType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtifactType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtifactType), nil
}

type OutboxStatus string

const (
	OutboxStatusPENDING    OutboxStatus = "PENDING"
	OutboxStatusPROCESSING OutboxStatus = "PROCESSING"
	OutboxStatusSENT       OutboxStatus = "SENT"
	OutboxStatusFAILED     OutboxStatus = "FAILED"
	OutboxStatusDEAD       OutboxStatus = "DEAD"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus `json:"outbox_status"`
	Valid        bool         `json:"valid"` // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type RiskLevel string

const (
	RiskLevelLOW      RiskLevel = "LOW"
	RiskLevelMEDIUM   RiskLevel = "MEDIUM"
	RiskLevelHIGH     RiskLevel = "HIGH"
	RiskLevelCRITICAL RiskLevel = "CRITICAL"
)

func (e *RiskLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiskLevel(s)
	case string:
		*e = RiskLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for RiskLevel: %T", src)
	}
	return nil
}

type NullRiskLevel struct {
	RiskLevel RiskLevel `json:"risk_level"`
	Valid     bool      `json:"valid"` // Valid is true if RiskLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiskLevel) Scan(value interface{}) error {
	if value == nil {
		ns.RiskLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiskLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiskLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiskLevel), nil
}

type TaskStatus string

const (
	TaskStatusQUEUED          TaskStatus = "QUEUED"
	TaskStatusRUNNING         TaskStatus = "RUNNING"
	TaskStatusWAITINGAPPROVAL TaskStatus = "WAITING_APPROVAL"
	TaskStatusPAUSED          TaskStatus = "PAUSED"
	TaskStatusCANCELING       TaskStatus = "CANCELING"
	TaskStatusCANCELED        TaskStatus = "CANCELED"
	TaskStatusSUCCEEDED       TaskStatus = "SUCCEEDED"
	TaskStatusFAILED          TaskStatus = "FAILED"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TenantStatus string

const (
	TenantStatusACTIVE    TenantStatus = "ACTIVE"
	TenantStatusSUSPENDED TenantStatus = "SUSPENDED"
	TenantStatusDELETED   TenantStatus = "DELETED"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus `json:"tenant_status"`
	Valid        bool         `json:"valid"` // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type ToolCallStatus string

const (
	ToolCallStatusPENDING         ToolCallStatus = "PENDING"
	ToolCallStatusRUNNING         ToolCallStatus = "RUNNING"
	ToolCallStatusWAITINGAPPROVAL ToolCallStatus = "WAITING_APPROVAL"
	ToolCallStatusSUCCEEDED       ToolCallStatus = "SUCCEEDED"
	ToolCallStatusFAILED          ToolCallStatus = "FAILED"
	ToolCallStatusCANCELED        ToolCallStatus = "CANCELED"
)

func (e *ToolCallStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ToolCallStatus(s)
	case string:
		*e = ToolCallStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ToolCallStatus: %T", src)
	}
	return nil
}

type NullToolCallStatus struct {
	ToolCallStatus ToolCallStatus `json:"tool_call_status"`
	Valid          bool           `json:"valid"` // Valid is true if ToolCallStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullToolCallStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ToolCallStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ToolCallStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullToolCallStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ToolCallStatus), nil
}

type ToolPolicyEffect string

const (
	ToolPolicyEffectALLOW           ToolPolicyEffect = "ALLOW"
	ToolPolicyEffectDENY            ToolPolicyEffect = "DENY"
	ToolPolicyEffectREQUIREAPPROVAL ToolPolicyEffect = "REQUIRE_APPROVAL"
)

func (e *ToolPolicyEffect) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ToolPolicyEffect(s)
	case string:
		*e = ToolPolicyEffect(s)
	default:
		return fmt.Errorf("unsupported scan type for ToolPolicyEffect: %T", src)
	}
	return nil
}

type NullToolPolicyEffect struct {
	ToolPolicyEffect ToolPolicyEffect `json:"tool_policy_effect"`
	Valid            bool             `json:"valid"` // Valid is true if ToolPolicyEffect is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullToolPolicyEffect) Scan(value interface{}) error {
	if value == nil {
		ns.ToolPolicyEffect, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ToolPolicyEffect.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullToolPolicyEffect) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ToolPolicyEffect), nil
}

type UserStatus string

const (
	UserStatusACTIVE   UserStatus = "ACTIVE"
	UserStatusDISABLED UserStatus = "DISABLED"
	UserStatusDELETED  UserStatus = "DELETED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AgentEvent struct {
	EventID   int64              `db:"event_id" json:"event_id"`
	TaskID    string             `db:"task_id" json:"task_id"`
	TenantID  string             `db:"tenant_id" json:"tenant_id"`
	Type      string             `db:"type" json:"type"`
	Input     json.RawMessage    `db:"input" json:"input"`
	Output    json.RawMessage    `db:"output" json:"output"`
	Metadata  json.RawMessage    `db:"metadata" json:"metadata"`
	TraceID   *string            `db:"trace_id" json:"trace_id"`
	SpanID    *string            `db:"span_id" json:"span_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AgentState struct {
	TaskID           string             `db:"task_id" json:"task_id"`
	TenantID         string             `db:"tenant_id" json:"tenant_id"`
	CurrentPlan      json.RawMessage    `db:"current_plan" json:"current_plan"`
	CurrentStep      int32              `db:"current_step" json:"current_step"`
	MemorySummary    *string            `db:"memory_summary" json:"memory_summary"`
	Constraints      json.RawMessage    `db:"constraints" json:"constraints"`
	Artifacts        json.RawMessage    `db:"artifacts" json:"artifacts"`
	LoopFingerprints json.RawMessage    `db:"loop_fingerprints" json:"loop_fingerprints"`
	Version          int32              `db:"version" json:"version"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AgentTask struct {
	TaskID           string             `db:"task_id" json:"task_id"`
	TenantID         string             `db:"tenant_id" json:"tenant_id"`
	UserID           string             `db:"user_id" json:"user_id"`
	Goal             string             `db:"goal" json:"goal"`
	Status           TaskStatus         `db:"status" json:"status"`
	Budget           json.RawMessage    `db:"budget" json:"budget"`
	BudgetUsage      json.RawMessage    `db:"budget_usage" json:"budget_usage"`
	WorkflowID       *string            `db:"workflow_id" json:"workflow_id"`
	TraceID          *string            `db:"trace_id" json:"trace_id"`
	LastErrorCode    *string            `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage *string            `db:"last_error_message" json:"last_error_message"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Approval struct {
	ApprovalID     string             `db:"approval_id" json:"approval_id"`
	TaskID         string             `db:"task_id" json:"task_id"`
	TenantID       string             `db:"tenant_id" json:"tenant_id"`
	CallID         string             `db:"call_id" json:"call_id"`
	ApproverID     *string            `db:"approver_id" json:"approver_id"`
	Status         ApprovalStatus     `db:"status" json:"status"`
	RiskLevel      RiskLevel          `db:"risk_level" json:"risk_level"`
	ApprovalReason *string            `db:"approval_reason" json:"approval_reason"`
	Comment        *string            `db:"comment" json:"comment"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	DecidedAt      pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Artifact struct {
	ArtifactID     string             `db:"artifact_id" json:"artifact_id"`
	TenantID       string             `db:"tenant_id" json:"tenant_id"`
	TaskID         string             `db:"task_id" json:"task_id"`
	UserID         string             `db:"user_id" json:"user_id"`
	Type           ArtifactType       `db:"type" json:"type"`
	Name           string             `db:"name" json:"name"`
	MediaType      *string            `db:"media_type" json:"media_type"`
	StorageBackend string             `db:"storage_backend" json:"storage_backend"`
	StorageKey     *string            `db:"storage_key" json:"storage_key"`
	ContentJson    json.RawMessage    `db:"content_json" json:"content_json"`
	SizeBytes      int64              `db:"size_bytes" json:"size_bytes"`
	ChecksumSha256 *string            `db:"checksum_sha256" json:"checksum_sha256"`
	Metadata       json.RawMessage    `db:"metadata" json:"metadata"`
	Status         ArtifactStatus     `db:"status" json:"status"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Checkpoint struct {
	CheckpointID  string             `db:"checkpoint_id" json:"checkpoint_id"`
	TaskID        string             `db:"task_id" json:"task_id"`
	TenantID      string             `db:"tenant_id" json:"tenant_id"`
	StateVersion  int32              `db:"state_version" json:"state_version"`
	EventOffset   int64              `db:"event_offset" json:"event_offset"`
	StateSnapshot json.RawMessage    `db:"state_snapshot" json:"state_snapshot"`
	Reason        string             `db:"reason" json:"reason"`
	TraceID       *string            `db:"trace_id" json:"trace_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TaskIdempotencyKey struct {
	TenantID        string             `db:"tenant_id" json:"tenant_id"`
	UserID          string             `db:"user_id" json:"user_id"`
	ClientRequestID string             `db:"client_request_id" json:"client_request_id"`
	TaskID          string             `db:"task_id" json:"task_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TaskOutbox struct {
	OutboxID      int64              `db:"outbox_id" json:"outbox_id"`
	TenantID      string             `db:"tenant_id" json:"tenant_id"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   string             `db:"aggregate_id" json:"aggregate_id"`
	EventType     string             `db:"event_type" json:"event_type"`
	Payload       json.RawMessage    `db:"payload" json:"payload"`
	Status        OutboxStatus       `db:"status" json:"status"`
	RetryCount    int32              `db:"retry_count" json:"retry_count"`
	NextRetryAt   pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Tenant struct {
	TenantID  string             `db:"tenant_id" json:"tenant_id"`
	Name      string             `db:"name" json:"name"`
	Status    TenantStatus       `db:"status" json:"status"`
	Metadata  json.RawMessage    `db:"metadata" json:"metadata"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TenantToolPolicy struct {
	PolicyID        string             `db:"policy_id" json:"policy_id"`
	TenantID        string             `db:"tenant_id" json:"tenant_id"`
	ToolName        string             `db:"tool_name" json:"tool_name"`
	Effect          ToolPolicyEffect   `db:"effect" json:"effect"`
	MaxRiskLevel    RiskLevel          `db:"max_risk_level" json:"max_risk_level"`
	RequireApproval bool               `db:"require_approval" json:"require_approval"`
	Config          json.RawMessage    `db:"config" json:"config"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ToolCall struct {
	CallID           string             `db:"call_id" json:"call_id"`
	TaskID           string             `db:"task_id" json:"task_id"`
	TenantID         string             `db:"tenant_id" json:"tenant_id"`
	UserID           string             `db:"user_id" json:"user_id"`
	ToolName         string             `db:"tool_name" json:"tool_name"`
	Arguments        json.RawMessage    `db:"arguments" json:"arguments"`
	ArgumentsHash    string             `db:"arguments_hash" json:"arguments_hash"`
	IdempotencyKey   string             `db:"idempotency_key" json:"idempotency_key"`
	Status           ToolCallStatus     `db:"status" json:"status"`
	Result           json.RawMessage    `db:"result" json:"result"`
	ResultArtifactID *string            `db:"result_artifact_id" json:"result_artifact_id"`
	RiskLevel        RiskLevel          `db:"risk_level" json:"risk_level"`
	ApprovalStatus   ApprovalStatus     `db:"approval_status" json:"approval_status"`
	ErrorCode        *string            `db:"error_code" json:"error_code"`
	ErrorMessage     *string            `db:"error_message" json:"error_message"`
	StartedAt        pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt       pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	TenantID    string             `db:"tenant_id" json:"tenant_id"`
	UserID      string             `db:"user_id" json:"user_id"`
	Email       string             `db:"email" json:"email"`
	DisplayName *string            `db:"display_name" json:"display_name"`
	Role        string             `db:"role" json:"role"`
	Status      UserStatus         `db:"status" json:"status"`
	Metadata    json.RawMessage    `db:"metadata" json:"metadata"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
