// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskOutboxMessage = `-- name: CreateTaskOutboxMessage :one
insert into task_outbox (
    tenant_id,
    aggregate_type,
    aggregate_id,
    event_type,
    payload,
    status,
    next_retry_at
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
returning outbox_id, tenant_id, aggregate_type, aggregate_id, event_type, payload, status, retry_count, next_retry_at, created_at, updated_at
`

type CreateTaskOutboxMessageParams struct {
	TenantID      string             `db:"tenant_id" json:"tenant_id"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   string             `db:"aggregate_id" json:"aggregate_id"`
	EventType     string             `db:"event_type" json:"event_type"`
	Payload       json.RawMessage    `db:"payload" json:"payload"`
	Status        OutboxStatus       `db:"status" json:"status"`
	NextRetryAt   pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
}

func (q *Queries) CreateTaskOutboxMessage(ctx context.Context, arg CreateTaskOutboxMessageParams) (TaskOutbox, error) {
	row := q.db.QueryRow(ctx, createTaskOutboxMessage,
		arg.TenantID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Status,
		arg.NextRetryAt,
	)
	var i TaskOutbox
	err := row.Scan(
		&i.OutboxID,
		&i.TenantID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingTaskOutboxMessages = `-- name: ListPendingTaskOutboxMessages :many
select outbox_id, tenant_id, aggregate_type, aggregate_id, event_type, payload, status, retry_count, next_retry_at, created_at, updated_at
from task_outbox
where status in ('PENDING', 'FAILED')
  and (next_retry_at is null or next_retry_at <= now())
order by created_at asc, outbox_id asc
limit $1
`

func (q *Queries) ListPendingTaskOutboxMessages(ctx context.Context, limitRows int32) ([]TaskOutbox, error) {
	rows, err := q.db.Query(ctx, listPendingTaskOutboxMessages, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskOutbox{}
	for rows.Next() {
		var i TaskOutbox
		if err := rows.Scan(
			&i.OutboxID,
			&i.TenantID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskOutboxFailed = `-- name: MarkTaskOutboxFailed :one
update task_outbox
set status = $1,
    retry_count = retry_count + 1,
    next_retry_at = $2,
    updated_at = now()
where outbox_id = $3
returning outbox_id, tenant_id, aggregate_type, aggregate_id, event_type, payload, status, retry_count, next_retry_at, created_at, updated_at
`

type MarkTaskOutboxFailedParams struct {
	Status      OutboxStatus       `db:"status" json:"status"`
	NextRetryAt pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
	OutboxID    int64              `db:"outbox_id" json:"outbox_id"`
}

func (q *Queries) MarkTaskOutboxFailed(ctx context.Context, arg MarkTaskOutboxFailedParams) (TaskOutbox, error) {
	row := q.db.QueryRow(ctx, markTaskOutboxFailed, arg.Status, arg.NextRetryAt, arg.OutboxID)
	var i TaskOutbox
	err := row.Scan(
		&i.OutboxID,
		&i.TenantID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markTaskOutboxProcessing = `-- name: MarkTaskOutboxProcessing :one
update task_outbox
set status = 'PROCESSING',
    updated_at = now()
where outbox_id = $1
  and status in ('PENDING', 'FAILED')
returning outbox_id, tenant_id, aggregate_type, aggregate_id, event_type, payload, status, retry_count, next_retry_at, created_at, updated_at
`

func (q *Queries) MarkTaskOutboxProcessing(ctx context.Context, outboxID int64) (TaskOutbox, error) {
	row := q.db.QueryRow(ctx, markTaskOutboxProcessing, outboxID)
	var i TaskOutbox
	err := row.Scan(
		&i.OutboxID,
		&i.TenantID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markTaskOutboxSent = `-- name: MarkTaskOutboxSent :one
update task_outbox
set status = 'SENT',
    updated_at = now()
where outbox_id = $1
returning outbox_id, tenant_id, aggregate_type, aggregate_id, event_type, payload, status, retry_count, next_retry_at, created_at, updated_at
`

func (q *Queries) MarkTaskOutboxSent(ctx context.Context, outboxID int64) (TaskOutbox, error) {
	row := q.db.QueryRow(ctx, markTaskOutboxSent, outboxID)
	var i TaskOutbox
	err := row.Scan(
		&i.OutboxID,
		&i.TenantID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetStaleTaskOutboxProcessing = `-- name: ResetStaleTaskOutboxProcessing :exec
update task_outbox
set status = 'FAILED',
    next_retry_at = now(),
    updated_at = now()
where status = 'PROCESSING'
  and updated_at < now() - $1::interval
`

func (q *Queries) ResetStaleTaskOutboxProcessing(ctx context.Context, staleAfter pgtype.Interval) error {
	_, err := q.db.Exec(ctx, resetStaleTaskOutboxProcessing, staleAfter)
	return err
}
