// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package db

import (
	"context"
	"encoding/json"
)

const getTenantToolPolicy = `-- name: GetTenantToolPolicy :one
select policy_id, tenant_id, tool_name, effect, max_risk_level, require_approval, config, created_at, updated_at
from tenant_tool_policies
where tenant_id = $1
  and tool_name = $2
limit 1
`

type GetTenantToolPolicyParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ToolName string `db:"tool_name" json:"tool_name"`
}

func (q *Queries) GetTenantToolPolicy(ctx context.Context, arg GetTenantToolPolicyParams) (TenantToolPolicy, error) {
	row := q.db.QueryRow(ctx, getTenantToolPolicy, arg.TenantID, arg.ToolName)
	var i TenantToolPolicy
	err := row.Scan(
		&i.PolicyID,
		&i.TenantID,
		&i.ToolName,
		&i.Effect,
		&i.MaxRiskLevel,
		&i.RequireApproval,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantToolPolicies = `-- name: ListTenantToolPolicies :many
select policy_id, tenant_id, tool_name, effect, max_risk_level, require_approval, config, created_at, updated_at
from tenant_tool_policies
where tenant_id = $1
order by tool_name asc
`

func (q *Queries) ListTenantToolPolicies(ctx context.Context, tenantID string) ([]TenantToolPolicy, error) {
	rows, err := q.db.Query(ctx, listTenantToolPolicies, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantToolPolicy{}
	for rows.Next() {
		var i TenantToolPolicy
		if err := rows.Scan(
			&i.PolicyID,
			&i.TenantID,
			&i.ToolName,
			&i.Effect,
			&i.MaxRiskLevel,
			&i.RequireApproval,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTenantToolPolicy = `-- name: UpsertTenantToolPolicy :one
insert into tenant_tool_policies (
    policy_id,
    tenant_id,
    tool_name,
    effect,
    max_risk_level,
    require_approval,
    config
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
on conflict (tenant_id, tool_name) do update
set effect = excluded.effect,
    max_risk_level = excluded.max_risk_level,
    require_approval = excluded.require_approval,
    config = excluded.config,
    updated_at = now()
returning policy_id, tenant_id, tool_name, effect, max_risk_level, require_approval, config, created_at, updated_at
`

type UpsertTenantToolPolicyParams struct {
	PolicyID        string           `db:"policy_id" json:"policy_id"`
	TenantID        string           `db:"tenant_id" json:"tenant_id"`
	ToolName        string           `db:"tool_name" json:"tool_name"`
	Effect          ToolPolicyEffect `db:"effect" json:"effect"`
	MaxRiskLevel    RiskLevel        `db:"max_risk_level" json:"max_risk_level"`
	RequireApproval bool             `db:"require_approval" json:"require_approval"`
	Config          json.RawMessage  `db:"config" json:"config"`
}

func (q *Queries) UpsertTenantToolPolicy(ctx context.Context, arg UpsertTenantToolPolicyParams) (TenantToolPolicy, error) {
	row := q.db.QueryRow(ctx, upsertTenantToolPolicy,
		arg.PolicyID,
		arg.TenantID,
		arg.ToolName,
		arg.Effect,
		arg.MaxRiskLevel,
		arg.RequireApproval,
		arg.Config,
	)
	var i TenantToolPolicy
	err := row.Scan(
		&i.PolicyID,
		&i.TenantID,
		&i.ToolName,
		&i.Effect,
		&i.MaxRiskLevel,
		&i.RequireApproval,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
