// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
	"encoding/json"
)

const getSystemSetting = `-- name: GetSystemSetting :one
select section, value, updated_by, updated_at
from system_settings
where section = $1
limit 1
`

func (q *Queries) GetSystemSetting(ctx context.Context, section string) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, getSystemSetting, section)
	var i SystemSetting
	err := row.Scan(
		&i.Section,
		&i.Value,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listSystemSettings = `-- name: ListSystemSettings :many
select section, value, updated_by, updated_at
from system_settings
order by section asc
`

func (q *Queries) ListSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.Query(ctx, listSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Section,
			&i.Value,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
insert into system_settings (section, value, updated_by)
values ($1, $2, $3)
on conflict (section) do update
set value = excluded.value,
    updated_by = excluded.updated_by,
    updated_at = now()
returning section, value, updated_by, updated_at
`

type UpsertSystemSettingParams struct {
	Section   string          `db:"section" json:"section"`
	Value     json.RawMessage `db:"value" json:"value"`
	UpdatedBy *string         `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRow(ctx, upsertSystemSetting, arg.Section, arg.Value, arg.UpdatedBy)
	var i SystemSetting
	err := row.Scan(
		&i.Section,
		&i.Value,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
