// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_templates.sql

package db

import (
	"context"
	"encoding/json"
)

const createTaskTemplate = `-- name: CreateTaskTemplate :one
insert into task_templates (
    template_id,
    tenant_id,
    name,
    payload,
    shared,
    created_by
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
returning template_id, tenant_id, name, payload, shared, created_by, created_at
`

type CreateTaskTemplateParams struct {
	TemplateID string          `db:"template_id" json:"template_id"`
	TenantID   string          `db:"tenant_id" json:"tenant_id"`
	Name       string          `db:"name" json:"name"`
	Payload    json.RawMessage `db:"payload" json:"payload"`
	Shared     bool            `db:"shared" json:"shared"`
	CreatedBy  string          `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateTaskTemplate(ctx context.Context, arg CreateTaskTemplateParams) (TaskTemplate, error) {
	row := q.db.QueryRow(ctx, createTaskTemplate,
		arg.TemplateID,
		arg.TenantID,
		arg.Name,
		arg.Payload,
		arg.Shared,
		arg.CreatedBy,
	)
	var i TaskTemplate
	err := row.Scan(
		&i.TemplateID,
		&i.TenantID,
		&i.Name,
		&i.Payload,
		&i.Shared,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTaskTemplate = `-- name: DeleteTaskTemplate :execrows
delete from task_templates
where tenant_id = $1
  and template_id = $2
`

type DeleteTaskTemplateParams struct {
	TenantID   string `db:"tenant_id" json:"tenant_id"`
	TemplateID string `db:"template_id" json:"template_id"`
}

func (q *Queries) DeleteTaskTemplate(ctx context.Context, arg DeleteTaskTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskTemplate, arg.TenantID, arg.TemplateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaskTemplate = `-- name: GetTaskTemplate :one
select template_id, tenant_id, name, payload, shared, created_by, created_at
from task_templates
where tenant_id = $1
  and template_id = $2
limit 1
`

type GetTaskTemplateParams struct {
	TenantID   string `db:"tenant_id" json:"tenant_id"`
	TemplateID string `db:"template_id" json:"template_id"`
}

func (q *Queries) GetTaskTemplate(ctx context.Context, arg GetTaskTemplateParams) (TaskTemplate, error) {
	row := q.db.QueryRow(ctx, getTaskTemplate, arg.TenantID, arg.TemplateID)
	var i TaskTemplate
	err := row.Scan(
		&i.TemplateID,
		&i.TenantID,
		&i.Name,
		&i.Payload,
		&i.Shared,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listTaskTemplatesForUser = `-- name: ListTaskTemplatesForUser :many
select template_id, tenant_id, name, payload, shared, created_by, created_at
from task_templates
where tenant_id = $1
  and (created_by = $2 or shared = true)
order by created_at desc
limit $4
offset $3
`

type ListTaskTemplatesForUserParams struct {
	TenantID   string `db:"tenant_id" json:"tenant_id"`
	CreatedBy  string `db:"created_by" json:"created_by"`
	OffsetRows int32  `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32  `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListTaskTemplatesForUser(ctx context.Context, arg ListTaskTemplatesForUserParams) ([]TaskTemplate, error) {
	rows, err := q.db.Query(ctx, listTaskTemplatesForUser,
		arg.TenantID,
		arg.CreatedBy,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskTemplate{}
	for rows.Next() {
		var i TaskTemplate
		if err := rows.Scan(
			&i.TemplateID,
			&i.TenantID,
			&i.Name,
			&i.Payload,
			&i.Shared,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
