// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
	"encoding/json"
)

const createAgentTask = `-- name: CreateAgentTask :one
insert into agent_tasks (
    task_id,
    tenant_id,
    user_id,
    goal,
    status,
    budget,
    budget_usage,
    trace_id
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
returning task_id, tenant_id, user_id, goal, status, budget, budget_usage, workflow_id, trace_id, last_error_code, last_error_message, created_at, updated_at
`

type CreateAgentTaskParams struct {
	TaskID      string          `db:"task_id" json:"task_id"`
	TenantID    string          `db:"tenant_id" json:"tenant_id"`
	UserID      string          `db:"user_id" json:"user_id"`
	Goal        string          `db:"goal" json:"goal"`
	Status      TaskStatus      `db:"status" json:"status"`
	Budget      json.RawMessage `db:"budget" json:"budget"`
	BudgetUsage json.RawMessage `db:"budget_usage" json:"budget_usage"`
	TraceID     *string         `db:"trace_id" json:"trace_id"`
}

func (q *Queries) CreateAgentTask(ctx context.Context, arg CreateAgentTaskParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, createAgentTask,
		arg.TaskID,
		arg.TenantID,
		arg.UserID,
		arg.Goal,
		arg.Status,
		arg.Budget,
		arg.BudgetUsage,
		arg.TraceID,
	)
	var i AgentTask
	err := row.Scan(
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.Budget,
		&i.BudgetUsage,
		&i.WorkflowID,
		&i.TraceID,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskIdempotencyKey = `-- name: CreateTaskIdempotencyKey :exec
insert into task_idempotency_keys (
    tenant_id,
    user_id,
    client_request_id,
    task_id
) values (
    $1,
    $2,
    $3,
    $4
)
`

type CreateTaskIdempotencyKeyParams struct {
	TenantID        string `db:"tenant_id" json:"tenant_id"`
	UserID          string `db:"user_id" json:"user_id"`
	ClientRequestID string `db:"client_request_id" json:"client_request_id"`
	TaskID          string `db:"task_id" json:"task_id"`
}

func (q *Queries) CreateTaskIdempotencyKey(ctx context.Context, arg CreateTaskIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, createTaskIdempotencyKey,
		arg.TenantID,
		arg.UserID,
		arg.ClientRequestID,
		arg.TaskID,
	)
	return err
}

const getAgentTask = `-- name: GetAgentTask :one
select task_id, tenant_id, user_id, goal, status, budget, budget_usage, workflow_id, trace_id, last_error_code, last_error_message, created_at, updated_at
from agent_tasks
where tenant_id = $1
  and task_id = $2
limit 1
`

type GetAgentTaskParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	TaskID   string `db:"task_id" json:"task_id"`
}

func (q *Queries) GetAgentTask(ctx context.Context, arg GetAgentTaskParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, getAgentTask, arg.TenantID, arg.TaskID)
	var i AgentTask
	err := row.Scan(
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.Budget,
		&i.BudgetUsage,
		&i.WorkflowID,
		&i.TraceID,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByClientRequestID = `-- name: GetTaskByClientRequestID :one
select agent_tasks.task_id, agent_tasks.tenant_id, agent_tasks.user_id, agent_tasks.goal, agent_tasks.status, agent_tasks.budget, agent_tasks.budget_usage, agent_tasks.workflow_id, agent_tasks.trace_id, agent_tasks.last_error_code, agent_tasks.last_error_message, agent_tasks.created_at, agent_tasks.updated_at
from task_idempotency_keys
join agent_tasks
  on agent_tasks.tenant_id = task_idempotency_keys.tenant_id
 and agent_tasks.task_id = task_idempotency_keys.task_id
where task_idempotency_keys.tenant_id = $1
  and task_idempotency_keys.user_id = $2
  and task_idempotency_keys.client_request_id = $3
limit 1
`

type GetTaskByClientRequestIDParams struct {
	TenantID        string `db:"tenant_id" json:"tenant_id"`
	UserID          string `db:"user_id" json:"user_id"`
	ClientRequestID string `db:"client_request_id" json:"client_request_id"`
}

func (q *Queries) GetTaskByClientRequestID(ctx context.Context, arg GetTaskByClientRequestIDParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, getTaskByClientRequestID, arg.TenantID, arg.UserID, arg.ClientRequestID)
	var i AgentTask
	err := row.Scan(
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.Budget,
		&i.BudgetUsage,
		&i.WorkflowID,
		&i.TraceID,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentTasksByTenant = `-- name: ListAgentTasksByTenant :many
select task_id, tenant_id, user_id, goal, status, budget, budget_usage, workflow_id, trace_id, last_error_code, last_error_message, created_at, updated_at
from agent_tasks
where tenant_id = $1
order by created_at desc, task_id desc
limit $3
offset $2
`

type ListAgentTasksByTenantParams struct {
	TenantID   string `db:"tenant_id" json:"tenant_id"`
	OffsetRows int32  `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32  `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListAgentTasksByTenant(ctx context.Context, arg ListAgentTasksByTenantParams) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listAgentTasksByTenant, arg.TenantID, arg.OffsetRows, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.TaskID,
			&i.TenantID,
			&i.UserID,
			&i.Goal,
			&i.Status,
			&i.Budget,
			&i.BudgetUsage,
			&i.WorkflowID,
			&i.TraceID,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTasksByTenantAndStatus = `-- name: ListAgentTasksByTenantAndStatus :many
select task_id, tenant_id, user_id, goal, status, budget, budget_usage, workflow_id, trace_id, last_error_code, last_error_message, created_at, updated_at
from agent_tasks
where tenant_id = $1
  and status = $2
order by created_at desc, task_id desc
limit $4
offset $3
`

type ListAgentTasksByTenantAndStatusParams struct {
	TenantID   string     `db:"tenant_id" json:"tenant_id"`
	Status     TaskStatus `db:"status" json:"status"`
	OffsetRows int32      `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32      `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListAgentTasksByTenantAndStatus(ctx context.Context, arg ListAgentTasksByTenantAndStatusParams) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listAgentTasksByTenantAndStatus,
		arg.TenantID,
		arg.Status,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.TaskID,
			&i.TenantID,
			&i.UserID,
			&i.Goal,
			&i.Status,
			&i.Budget,
			&i.BudgetUsage,
			&i.WorkflowID,
			&i.TraceID,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTasksByUser = `-- name: ListAgentTasksByUser :many
select task_id, tenant_id, user_id, goal, status, budget, budget_usage, workflow_id, trace_id, last_error_code, last_error_message, created_at, updated_at
from agent_tasks
where tenant_id = $1
  and user_id = $2
order by created_at desc, task_id desc
limit $4
offset $3
`

type ListAgentTasksByUserParams struct {
	TenantID   string `db:"tenant_id" json:"tenant_id"`
	UserID     string `db:"user_id" json:"user_id"`
	OffsetRows int32  `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32  `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListAgentTasksByUser(ctx context.Context, arg ListAgentTasksByUserParams) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listAgentTasksByUser,
		arg.TenantID,
		arg.UserID,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.TaskID,
			&i.TenantID,
			&i.UserID,
			&i.Goal,
			&i.Status,
			&i.Budget,
			&i.BudgetUsage,
			&i.WorkflowID,
			&i.TraceID,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTasksByUserAndStatus = `-- name: ListAgentTasksByUserAndStatus :many
select task_id, tenant_id, user_id, goal, status, budget, budget_usage, workflow_id, trace_id, last_error_code, last_error_message, created_at, updated_at
from agent_tasks
where tenant_id = $1
  and user_id = $2
  and status = $3
order by created_at desc, task_id desc
limit $5
offset $4
`

type ListAgentTasksByUserAndStatusParams struct {
	TenantID   string     `db:"tenant_id" json:"tenant_id"`
	UserID     string     `db:"user_id" json:"user_id"`
	Status     TaskStatus `db:"status" json:"status"`
	OffsetRows int32      `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32      `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListAgentTasksByUserAndStatus(ctx context.Context, arg ListAgentTasksByUserAndStatusParams) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listAgentTasksByUserAndStatus,
		arg.TenantID,
		arg.UserID,
		arg.Status,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.TaskID,
			&i.TenantID,
			&i.UserID,
			&i.Goal,
			&i.Status,
			&i.Budget,
			&i.BudgetUsage,
			&i.WorkflowID,
			&i.TraceID,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnableAgentTasks = `-- name: ListRunnableAgentTasks :many
select task_id, tenant_id, user_id, goal, status, budget, budget_usage, workflow_id, trace_id, last_error_code, last_error_message, created_at, updated_at
from agent_tasks
where status in ('QUEUED', 'CANCELING')
order by updated_at asc, task_id asc
limit $1
`

func (q *Queries) ListRunnableAgentTasks(ctx context.Context, limitRows int32) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listRunnableAgentTasks, limitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.TaskID,
			&i.TenantID,
			&i.UserID,
			&i.Goal,
			&i.Status,
			&i.Budget,
			&i.BudgetUsage,
			&i.WorkflowID,
			&i.TraceID,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentTaskFailed = `-- name: MarkAgentTaskFailed :one
update agent_tasks
set status = 'FAILED',
    last_error_code = $1,
    last_error_message = $2,
    updated_at = now()
where tenant_id = $3
  and task_id = $4
returning task_id, tenant_id, user_id, goal, status, budget, budget_usage, workflow_id, trace_id, last_error_code, last_error_message, created_at, updated_at
`

type MarkAgentTaskFailedParams struct {
	LastErrorCode    *string `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage *string `db:"last_error_message" json:"last_error_message"`
	TenantID         string  `db:"tenant_id" json:"tenant_id"`
	TaskID           string  `db:"task_id" json:"task_id"`
}

func (q *Queries) MarkAgentTaskFailed(ctx context.Context, arg MarkAgentTaskFailedParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, markAgentTaskFailed,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.TenantID,
		arg.TaskID,
	)
	var i AgentTask
	err := row.Scan(
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.Budget,
		&i.BudgetUsage,
		&i.WorkflowID,
		&i.TraceID,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAgentTaskStopped = `-- name: MarkAgentTaskStopped :one
update agent_tasks
set status = 'STOPPED_BY_LIMIT',
    last_error_code = $1,
    last_error_message = $2,
    updated_at = now()
where tenant_id = $3
  and task_id = $4
returning task_id, tenant_id, user_id, goal, status, budget, budget_usage, workflow_id, trace_id, last_error_code, last_error_message, created_at, updated_at
`

type MarkAgentTaskStoppedParams struct {
	LastErrorCode    *string `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage *string `db:"last_error_message" json:"last_error_message"`
	TenantID         string  `db:"tenant_id" json:"tenant_id"`
	TaskID           string  `db:"task_id" json:"task_id"`
}

func (q *Queries) MarkAgentTaskStopped(ctx context.Context, arg MarkAgentTaskStoppedParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, markAgentTaskStopped,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.TenantID,
		arg.TaskID,
	)
	var i AgentTask
	err := row.Scan(
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.Budget,
		&i.BudgetUsage,
		&i.WorkflowID,
		&i.TraceID,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentTaskBudgetUsage = `-- name: UpdateAgentTaskBudgetUsage :one
update agent_tasks
set budget_usage = $1,
    updated_at = now()
where tenant_id = $2
  and task_id = $3
returning task_id, tenant_id, user_id, goal, status, budget, budget_usage, workflow_id, trace_id, last_error_code, last_error_message, created_at, updated_at
`

type UpdateAgentTaskBudgetUsageParams struct {
	BudgetUsage json.RawMessage `db:"budget_usage" json:"budget_usage"`
	TenantID    string          `db:"tenant_id" json:"tenant_id"`
	TaskID      string          `db:"task_id" json:"task_id"`
}

func (q *Queries) UpdateAgentTaskBudgetUsage(ctx context.Context, arg UpdateAgentTaskBudgetUsageParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, updateAgentTaskBudgetUsage, arg.BudgetUsage, arg.TenantID, arg.TaskID)
	var i AgentTask
	err := row.Scan(
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.Budget,
		&i.BudgetUsage,
		&i.WorkflowID,
		&i.TraceID,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentTaskStatus = `-- name: UpdateAgentTaskStatus :one
update agent_tasks
set status = $1,
    updated_at = now()
where tenant_id = $2
  and task_id = $3
returning task_id, tenant_id, user_id, goal, status, budget, budget_usage, workflow_id, trace_id, last_error_code, last_error_message, created_at, updated_at
`

type UpdateAgentTaskStatusParams struct {
	Status   TaskStatus `db:"status" json:"status"`
	TenantID string     `db:"tenant_id" json:"tenant_id"`
	TaskID   string     `db:"task_id" json:"task_id"`
}

func (q *Queries) UpdateAgentTaskStatus(ctx context.Context, arg UpdateAgentTaskStatusParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, updateAgentTaskStatus, arg.Status, arg.TenantID, arg.TaskID)
	var i AgentTask
	err := row.Scan(
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.Budget,
		&i.BudgetUsage,
		&i.WorkflowID,
		&i.TraceID,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentTaskStatusIfCurrent = `-- name: UpdateAgentTaskStatusIfCurrent :one
update agent_tasks
set status = $1,
    updated_at = now()
where tenant_id = $2
  and task_id = $3
  and status = $4
returning task_id, tenant_id, user_id, goal, status, budget, budget_usage, workflow_id, trace_id, last_error_code, last_error_message, created_at, updated_at
`

type UpdateAgentTaskStatusIfCurrentParams struct {
	NextStatus    TaskStatus `db:"next_status" json:"next_status"`
	TenantID      string     `db:"tenant_id" json:"tenant_id"`
	TaskID        string     `db:"task_id" json:"task_id"`
	CurrentStatus TaskStatus `db:"current_status" json:"current_status"`
}

func (q *Queries) UpdateAgentTaskStatusIfCurrent(ctx context.Context, arg UpdateAgentTaskStatusIfCurrentParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, updateAgentTaskStatusIfCurrent,
		arg.NextStatus,
		arg.TenantID,
		arg.TaskID,
		arg.CurrentStatus,
	)
	var i AgentTask
	err := row.Scan(
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.Budget,
		&i.BudgetUsage,
		&i.WorkflowID,
		&i.TraceID,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentTaskWorkflow = `-- name: UpdateAgentTaskWorkflow :one
update agent_tasks
set workflow_id = $1,
    trace_id = $2,
    updated_at = now()
where tenant_id = $3
  and task_id = $4
returning task_id, tenant_id, user_id, goal, status, budget, budget_usage, workflow_id, trace_id, last_error_code, last_error_message, created_at, updated_at
`

type UpdateAgentTaskWorkflowParams struct {
	WorkflowID *string `db:"workflow_id" json:"workflow_id"`
	TraceID    *string `db:"trace_id" json:"trace_id"`
	TenantID   string  `db:"tenant_id" json:"tenant_id"`
	TaskID     string  `db:"task_id" json:"task_id"`
}

func (q *Queries) UpdateAgentTaskWorkflow(ctx context.Context, arg UpdateAgentTaskWorkflowParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, updateAgentTaskWorkflow,
		arg.WorkflowID,
		arg.TraceID,
		arg.TenantID,
		arg.TaskID,
	)
	var i AgentTask
	err := row.Scan(
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.Goal,
		&i.Status,
		&i.Budget,
		&i.BudgetUsage,
		&i.WorkflowID,
		&i.TraceID,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
