// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"
	"encoding/json"
)

const createTenant = `-- name: CreateTenant :one
insert into tenants (
    tenant_id,
    name,
    status,
    metadata
) values (
    $1,
    $2,
    $3,
    $4
)
returning tenant_id, name, status, metadata, created_at, updated_at
`

type CreateTenantParams struct {
	TenantID string          `db:"tenant_id" json:"tenant_id"`
	Name     string          `db:"name" json:"name"`
	Status   TenantStatus    `db:"status" json:"status"`
	Metadata json.RawMessage `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.TenantID,
		arg.Name,
		arg.Status,
		arg.Metadata,
	)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (
    tenant_id,
    user_id,
    email,
    display_name,
    role,
    status,
    metadata
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
returning tenant_id, user_id, email, display_name, role, status, metadata, created_at, updated_at
`

type CreateUserParams struct {
	TenantID    string          `db:"tenant_id" json:"tenant_id"`
	UserID      string          `db:"user_id" json:"user_id"`
	Email       string          `db:"email" json:"email"`
	DisplayName *string         `db:"display_name" json:"display_name"`
	Role        string          `db:"role" json:"role"`
	Status      UserStatus      `db:"status" json:"status"`
	Metadata    json.RawMessage `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.UserID,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.Status,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
select tenant_id, name, status, metadata, created_at, updated_at
from tenants
where tenant_id = $1
limit 1
`

func (q *Queries) GetTenant(ctx context.Context, tenantID string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, tenantID)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select tenant_id, user_id, email, display_name, role, status, metadata, created_at, updated_at
from users
where tenant_id = $1
  and user_id = $2
limit 1
`

type GetUserParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	UserID   string `db:"user_id" json:"user_id"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.TenantID, arg.UserID)
	var i User
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
