// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tool_calls.sql

package db

import (
	"context"
	"encoding/json"
)

const completeToolCall = `-- name: CompleteToolCall :one
update tool_calls
set status = 'SUCCEEDED',
    result = $1,
    result_artifact_id = $2,
    finished_at = now(),
    updated_at = now()
where tenant_id = $3
  and call_id = $4
returning call_id, task_id, tenant_id, user_id, tool_name, arguments, arguments_hash, idempotency_key, status, result, result_artifact_id, risk_level, approval_status, error_code, error_message, started_at, finished_at, created_at, updated_at
`

type CompleteToolCallParams struct {
	Result           json.RawMessage `db:"result" json:"result"`
	ResultArtifactID *string         `db:"result_artifact_id" json:"result_artifact_id"`
	TenantID         string          `db:"tenant_id" json:"tenant_id"`
	CallID           string          `db:"call_id" json:"call_id"`
}

func (q *Queries) CompleteToolCall(ctx context.Context, arg CompleteToolCallParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, completeToolCall,
		arg.Result,
		arg.ResultArtifactID,
		arg.TenantID,
		arg.CallID,
	)
	var i ToolCall
	err := row.Scan(
		&i.CallID,
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.ToolName,
		&i.Arguments,
		&i.ArgumentsHash,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.ResultArtifactID,
		&i.RiskLevel,
		&i.ApprovalStatus,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createToolCall = `-- name: CreateToolCall :one
insert into tool_calls (
    call_id,
    tenant_id,
    task_id,
    user_id,
    tool_name,
    arguments,
    arguments_hash,
    idempotency_key,
    status,
    risk_level,
    approval_status
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
returning call_id, task_id, tenant_id, user_id, tool_name, arguments, arguments_hash, idempotency_key, status, result, result_artifact_id, risk_level, approval_status, error_code, error_message, started_at, finished_at, created_at, updated_at
`

type CreateToolCallParams struct {
	CallID         string          `db:"call_id" json:"call_id"`
	TenantID       string          `db:"tenant_id" json:"tenant_id"`
	TaskID         string          `db:"task_id" json:"task_id"`
	UserID         string          `db:"user_id" json:"user_id"`
	ToolName       string          `db:"tool_name" json:"tool_name"`
	Arguments      json.RawMessage `db:"arguments" json:"arguments"`
	ArgumentsHash  string          `db:"arguments_hash" json:"arguments_hash"`
	IdempotencyKey string          `db:"idempotency_key" json:"idempotency_key"`
	Status         ToolCallStatus  `db:"status" json:"status"`
	RiskLevel      RiskLevel       `db:"risk_level" json:"risk_level"`
	ApprovalStatus ApprovalStatus  `db:"approval_status" json:"approval_status"`
}

func (q *Queries) CreateToolCall(ctx context.Context, arg CreateToolCallParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, createToolCall,
		arg.CallID,
		arg.TenantID,
		arg.TaskID,
		arg.UserID,
		arg.ToolName,
		arg.Arguments,
		arg.ArgumentsHash,
		arg.IdempotencyKey,
		arg.Status,
		arg.RiskLevel,
		arg.ApprovalStatus,
	)
	var i ToolCall
	err := row.Scan(
		&i.CallID,
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.ToolName,
		&i.Arguments,
		&i.ArgumentsHash,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.ResultArtifactID,
		&i.RiskLevel,
		&i.ApprovalStatus,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failToolCall = `-- name: FailToolCall :one
update tool_calls
set status = 'FAILED',
    error_code = $1,
    error_message = $2,
    finished_at = now(),
    updated_at = now()
where tenant_id = $3
  and call_id = $4
returning call_id, task_id, tenant_id, user_id, tool_name, arguments, arguments_hash, idempotency_key, status, result, result_artifact_id, risk_level, approval_status, error_code, error_message, started_at, finished_at, created_at, updated_at
`

type FailToolCallParams struct {
	ErrorCode    *string `db:"error_code" json:"error_code"`
	ErrorMessage *string `db:"error_message" json:"error_message"`
	TenantID     string  `db:"tenant_id" json:"tenant_id"`
	CallID       string  `db:"call_id" json:"call_id"`
}

func (q *Queries) FailToolCall(ctx context.Context, arg FailToolCallParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, failToolCall,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.TenantID,
		arg.CallID,
	)
	var i ToolCall
	err := row.Scan(
		&i.CallID,
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.ToolName,
		&i.Arguments,
		&i.ArgumentsHash,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.ResultArtifactID,
		&i.RiskLevel,
		&i.ApprovalStatus,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolCall = `-- name: GetToolCall :one
select call_id, task_id, tenant_id, user_id, tool_name, arguments, arguments_hash, idempotency_key, status, result, result_artifact_id, risk_level, approval_status, error_code, error_message, started_at, finished_at, created_at, updated_at
from tool_calls
where tenant_id = $1
  and call_id = $2
limit 1
`

type GetToolCallParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	CallID   string `db:"call_id" json:"call_id"`
}

func (q *Queries) GetToolCall(ctx context.Context, arg GetToolCallParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, getToolCall, arg.TenantID, arg.CallID)
	var i ToolCall
	err := row.Scan(
		&i.CallID,
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.ToolName,
		&i.Arguments,
		&i.ArgumentsHash,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.ResultArtifactID,
		&i.RiskLevel,
		&i.ApprovalStatus,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolCallByIdempotencyKey = `-- name: GetToolCallByIdempotencyKey :one
select call_id, task_id, tenant_id, user_id, tool_name, arguments, arguments_hash, idempotency_key, status, result, result_artifact_id, risk_level, approval_status, error_code, error_message, started_at, finished_at, created_at, updated_at
from tool_calls
where tenant_id = $1
  and idempotency_key = $2
limit 1
`

type GetToolCallByIdempotencyKeyParams struct {
	TenantID       string `db:"tenant_id" json:"tenant_id"`
	IdempotencyKey string `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetToolCallByIdempotencyKey(ctx context.Context, arg GetToolCallByIdempotencyKeyParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, getToolCallByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i ToolCall
	err := row.Scan(
		&i.CallID,
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.ToolName,
		&i.Arguments,
		&i.ArgumentsHash,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.ResultArtifactID,
		&i.RiskLevel,
		&i.ApprovalStatus,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listToolCallsByTask = `-- name: ListToolCallsByTask :many
select call_id, task_id, tenant_id, user_id, tool_name, arguments, arguments_hash, idempotency_key, status, result, result_artifact_id, risk_level, approval_status, error_code, error_message, started_at, finished_at, created_at, updated_at
from tool_calls
where tenant_id = $1
  and task_id = $2
order by created_at asc, call_id asc
limit $4
offset $3
`

type ListToolCallsByTaskParams struct {
	TenantID   string `db:"tenant_id" json:"tenant_id"`
	TaskID     string `db:"task_id" json:"task_id"`
	OffsetRows int32  `db:"offset_rows" json:"offset_rows"`
	LimitRows  int32  `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListToolCallsByTask(ctx context.Context, arg ListToolCallsByTaskParams) ([]ToolCall, error) {
	rows, err := q.db.Query(ctx, listToolCallsByTask,
		arg.TenantID,
		arg.TaskID,
		arg.OffsetRows,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolCall{}
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.CallID,
			&i.TaskID,
			&i.TenantID,
			&i.UserID,
			&i.ToolName,
			&i.Arguments,
			&i.ArgumentsHash,
			&i.IdempotencyKey,
			&i.Status,
			&i.Result,
			&i.ResultArtifactID,
			&i.RiskLevel,
			&i.ApprovalStatus,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCallsByTaskStatus = `-- name: ListToolCallsByTaskStatus :many
select call_id, task_id, tenant_id, user_id, tool_name, arguments, arguments_hash, idempotency_key, status, result, result_artifact_id, risk_level, approval_status, error_code, error_message, started_at, finished_at, created_at, updated_at
from tool_calls
where tenant_id = $1
  and task_id = $2
  and status = $3
order by created_at asc, call_id asc
limit $4
`

type ListToolCallsByTaskStatusParams struct {
	TenantID  string         `db:"tenant_id" json:"tenant_id"`
	TaskID    string         `db:"task_id" json:"task_id"`
	Status    ToolCallStatus `db:"status" json:"status"`
	LimitRows int32          `db:"limit_rows" json:"limit_rows"`
}

func (q *Queries) ListToolCallsByTaskStatus(ctx context.Context, arg ListToolCallsByTaskStatusParams) ([]ToolCall, error) {
	rows, err := q.db.Query(ctx, listToolCallsByTaskStatus,
		arg.TenantID,
		arg.TaskID,
		arg.Status,
		arg.LimitRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolCall{}
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.CallID,
			&i.TaskID,
			&i.TenantID,
			&i.UserID,
			&i.ToolName,
			&i.Arguments,
			&i.ArgumentsHash,
			&i.IdempotencyKey,
			&i.Status,
			&i.Result,
			&i.ResultArtifactID,
			&i.RiskLevel,
			&i.ApprovalStatus,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startToolCall = `-- name: StartToolCall :one
update tool_calls
set status = 'RUNNING',
    started_at = coalesce(started_at, now()),
    updated_at = now()
where tenant_id = $1
  and call_id = $2
returning call_id, task_id, tenant_id, user_id, tool_name, arguments, arguments_hash, idempotency_key, status, result, result_artifact_id, risk_level, approval_status, error_code, error_message, started_at, finished_at, created_at, updated_at
`

type StartToolCallParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	CallID   string `db:"call_id" json:"call_id"`
}

func (q *Queries) StartToolCall(ctx context.Context, arg StartToolCallParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, startToolCall, arg.TenantID, arg.CallID)
	var i ToolCall
	err := row.Scan(
		&i.CallID,
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.ToolName,
		&i.Arguments,
		&i.ArgumentsHash,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.ResultArtifactID,
		&i.RiskLevel,
		&i.ApprovalStatus,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateToolCallApprovalStatus = `-- name: UpdateToolCallApprovalStatus :one
update tool_calls
set approval_status = $1,
    updated_at = now()
where tenant_id = $2
  and call_id = $3
returning call_id, task_id, tenant_id, user_id, tool_name, arguments, arguments_hash, idempotency_key, status, result, result_artifact_id, risk_level, approval_status, error_code, error_message, started_at, finished_at, created_at, updated_at
`

type UpdateToolCallApprovalStatusParams struct {
	ApprovalStatus ApprovalStatus `db:"approval_status" json:"approval_status"`
	TenantID       string         `db:"tenant_id" json:"tenant_id"`
	CallID         string         `db:"call_id" json:"call_id"`
}

func (q *Queries) UpdateToolCallApprovalStatus(ctx context.Context, arg UpdateToolCallApprovalStatusParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, updateToolCallApprovalStatus, arg.ApprovalStatus, arg.TenantID, arg.CallID)
	var i ToolCall
	err := row.Scan(
		&i.CallID,
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.ToolName,
		&i.Arguments,
		&i.ArgumentsHash,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.ResultArtifactID,
		&i.RiskLevel,
		&i.ApprovalStatus,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateToolCallStatusAndApproval = `-- name: UpdateToolCallStatusAndApproval :one
update tool_calls
set status = $1,
    approval_status = $2,
    updated_at = now()
where tenant_id = $3
  and call_id = $4
returning call_id, task_id, tenant_id, user_id, tool_name, arguments, arguments_hash, idempotency_key, status, result, result_artifact_id, risk_level, approval_status, error_code, error_message, started_at, finished_at, created_at, updated_at
`

type UpdateToolCallStatusAndApprovalParams struct {
	Status         ToolCallStatus `db:"status" json:"status"`
	ApprovalStatus ApprovalStatus `db:"approval_status" json:"approval_status"`
	TenantID       string         `db:"tenant_id" json:"tenant_id"`
	CallID         string         `db:"call_id" json:"call_id"`
}

func (q *Queries) UpdateToolCallStatusAndApproval(ctx context.Context, arg UpdateToolCallStatusAndApprovalParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, updateToolCallStatusAndApproval,
		arg.Status,
		arg.ApprovalStatus,
		arg.TenantID,
		arg.CallID,
	)
	var i ToolCall
	err := row.Scan(
		&i.CallID,
		&i.TaskID,
		&i.TenantID,
		&i.UserID,
		&i.ToolName,
		&i.Arguments,
		&i.ArgumentsHash,
		&i.IdempotencyKey,
		&i.Status,
		&i.Result,
		&i.ResultArtifactID,
		&i.RiskLevel,
		&i.ApprovalStatus,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
