// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tools.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTool = `-- name: GetTool :one
select tool_name, description, category, default_risk_level, enabled, version, owner, has_side_effect, requires_idempotency_key, timeout_seconds, params_schema, result_schema, retry_policy, created_at, updated_at
from tools
where tool_name = $1
limit 1
`

func (q *Queries) GetTool(ctx context.Context, toolName string) (Tool, error) {
	row := q.db.QueryRow(ctx, getTool, toolName)
	var i Tool
	err := row.Scan(
		&i.ToolName,
		&i.Description,
		&i.Category,
		&i.DefaultRiskLevel,
		&i.Enabled,
		&i.Version,
		&i.Owner,
		&i.HasSideEffect,
		&i.RequiresIdempotencyKey,
		&i.TimeoutSeconds,
		&i.ParamsSchema,
		&i.ResultSchema,
		&i.RetryPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledTools = `-- name: ListEnabledTools :many
select tool_name, description, category, default_risk_level, enabled, version, owner, has_side_effect, requires_idempotency_key, timeout_seconds, params_schema, result_schema, retry_policy, created_at, updated_at
from tools
where enabled = true
order by tool_name asc
`

func (q *Queries) ListEnabledTools(ctx context.Context) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listEnabledTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tool{}
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ToolName,
			&i.Description,
			&i.Category,
			&i.DefaultRiskLevel,
			&i.Enabled,
			&i.Version,
			&i.Owner,
			&i.HasSideEffect,
			&i.RequiresIdempotencyKey,
			&i.TimeoutSeconds,
			&i.ParamsSchema,
			&i.ResultSchema,
			&i.RetryPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTools = `-- name: ListTools :many
select tool_name, description, category, default_risk_level, enabled, version, owner, has_side_effect, requires_idempotency_key, timeout_seconds, params_schema, result_schema, retry_policy, created_at, updated_at
from tools
order by tool_name asc
`

func (q *Queries) ListTools(ctx context.Context) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tool{}
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ToolName,
			&i.Description,
			&i.Category,
			&i.DefaultRiskLevel,
			&i.Enabled,
			&i.Version,
			&i.Owner,
			&i.HasSideEffect,
			&i.RequiresIdempotencyKey,
			&i.TimeoutSeconds,
			&i.ParamsSchema,
			&i.ResultSchema,
			&i.RetryPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toolCallStatsByTool = `-- name: ToolCallStatsByTool :one
select
    count(*)::bigint as calls_total,
    coalesce(sum(case when status = 'FAILED' then 1 else 0 end), 0)::bigint as error_total,
    coalesce(avg(extract(epoch from (finished_at - started_at)) * 1000) filter (where finished_at is not null and started_at is not null), 0)::float8 as avg_duration_ms
from tool_calls
where tool_name = $1
  and created_at >= $2
`

type ToolCallStatsByToolParams struct {
	ToolName string             `db:"tool_name" json:"tool_name"`
	Since    pgtype.Timestamptz `db:"since" json:"since"`
}

type ToolCallStatsByToolRow struct {
	CallsTotal    int64   `db:"calls_total" json:"calls_total"`
	ErrorTotal    int64   `db:"error_total" json:"error_total"`
	AvgDurationMs float64 `db:"avg_duration_ms" json:"avg_duration_ms"`
}

func (q *Queries) ToolCallStatsByTool(ctx context.Context, arg ToolCallStatsByToolParams) (ToolCallStatsByToolRow, error) {
	row := q.db.QueryRow(ctx, toolCallStatsByTool, arg.ToolName, arg.Since)
	var i ToolCallStatsByToolRow
	err := row.Scan(&i.CallsTotal, &i.ErrorTotal, &i.AvgDurationMs)
	return i, err
}

const updateTool = `-- name: UpdateTool :one
update tools
set enabled = $1,
    default_risk_level = $2,
    timeout_seconds = $3,
    description = $4,
    category = $5,
    params_schema = $6,
    retry_policy = $7,
    updated_at = now()
where tool_name = $8
returning tool_name, description, category, default_risk_level, enabled, version, owner, has_side_effect, requires_idempotency_key, timeout_seconds, params_schema, result_schema, retry_policy, created_at, updated_at
`

type UpdateToolParams struct {
	Enabled          bool            `db:"enabled" json:"enabled"`
	DefaultRiskLevel RiskLevel       `db:"default_risk_level" json:"default_risk_level"`
	TimeoutSeconds   int32           `db:"timeout_seconds" json:"timeout_seconds"`
	Description      string          `db:"description" json:"description"`
	Category         string          `db:"category" json:"category"`
	ParamsSchema     json.RawMessage `db:"params_schema" json:"params_schema"`
	RetryPolicy      json.RawMessage `db:"retry_policy" json:"retry_policy"`
	ToolName         string          `db:"tool_name" json:"tool_name"`
}

func (q *Queries) UpdateTool(ctx context.Context, arg UpdateToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, updateTool,
		arg.Enabled,
		arg.DefaultRiskLevel,
		arg.TimeoutSeconds,
		arg.Description,
		arg.Category,
		arg.ParamsSchema,
		arg.RetryPolicy,
		arg.ToolName,
	)
	var i Tool
	err := row.Scan(
		&i.ToolName,
		&i.Description,
		&i.Category,
		&i.DefaultRiskLevel,
		&i.Enabled,
		&i.Version,
		&i.Owner,
		&i.HasSideEffect,
		&i.RequiresIdempotencyKey,
		&i.TimeoutSeconds,
		&i.ParamsSchema,
		&i.ResultSchema,
		&i.RetryPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
