// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: states.sql

package db

import (
	"context"
	"encoding/json"
)

const createAgentState = `-- name: CreateAgentState :one
insert into agent_states (
    tenant_id,
    task_id,
    current_plan,
    current_step,
    memory_summary,
    constraints,
    artifacts,
    loop_fingerprints
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
returning task_id, tenant_id, current_plan, current_step, memory_summary, constraints, artifacts, loop_fingerprints, version, updated_at
`

type CreateAgentStateParams struct {
	TenantID         string          `db:"tenant_id" json:"tenant_id"`
	TaskID           string          `db:"task_id" json:"task_id"`
	CurrentPlan      json.RawMessage `db:"current_plan" json:"current_plan"`
	CurrentStep      int32           `db:"current_step" json:"current_step"`
	MemorySummary    *string         `db:"memory_summary" json:"memory_summary"`
	Constraints      json.RawMessage `db:"constraints" json:"constraints"`
	Artifacts        json.RawMessage `db:"artifacts" json:"artifacts"`
	LoopFingerprints json.RawMessage `db:"loop_fingerprints" json:"loop_fingerprints"`
}

func (q *Queries) CreateAgentState(ctx context.Context, arg CreateAgentStateParams) (AgentState, error) {
	row := q.db.QueryRow(ctx, createAgentState,
		arg.TenantID,
		arg.TaskID,
		arg.CurrentPlan,
		arg.CurrentStep,
		arg.MemorySummary,
		arg.Constraints,
		arg.Artifacts,
		arg.LoopFingerprints,
	)
	var i AgentState
	err := row.Scan(
		&i.TaskID,
		&i.TenantID,
		&i.CurrentPlan,
		&i.CurrentStep,
		&i.MemorySummary,
		&i.Constraints,
		&i.Artifacts,
		&i.LoopFingerprints,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentState = `-- name: GetAgentState :one
select task_id, tenant_id, current_plan, current_step, memory_summary, constraints, artifacts, loop_fingerprints, version, updated_at
from agent_states
where tenant_id = $1
  and task_id = $2
limit 1
`

type GetAgentStateParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	TaskID   string `db:"task_id" json:"task_id"`
}

func (q *Queries) GetAgentState(ctx context.Context, arg GetAgentStateParams) (AgentState, error) {
	row := q.db.QueryRow(ctx, getAgentState, arg.TenantID, arg.TaskID)
	var i AgentState
	err := row.Scan(
		&i.TaskID,
		&i.TenantID,
		&i.CurrentPlan,
		&i.CurrentStep,
		&i.MemorySummary,
		&i.Constraints,
		&i.Artifacts,
		&i.LoopFingerprints,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentStateOptimistic = `-- name: UpdateAgentStateOptimistic :one
update agent_states
set current_plan = $1,
    current_step = $2,
    memory_summary = $3,
    constraints = $4,
    artifacts = $5,
    loop_fingerprints = $6,
    version = version + 1,
    updated_at = now()
where tenant_id = $7
  and task_id = $8
  and version = $9
returning task_id, tenant_id, current_plan, current_step, memory_summary, constraints, artifacts, loop_fingerprints, version, updated_at
`

type UpdateAgentStateOptimisticParams struct {
	CurrentPlan      json.RawMessage `db:"current_plan" json:"current_plan"`
	CurrentStep      int32           `db:"current_step" json:"current_step"`
	MemorySummary    *string         `db:"memory_summary" json:"memory_summary"`
	Constraints      json.RawMessage `db:"constraints" json:"constraints"`
	Artifacts        json.RawMessage `db:"artifacts" json:"artifacts"`
	LoopFingerprints json.RawMessage `db:"loop_fingerprints" json:"loop_fingerprints"`
	TenantID         string          `db:"tenant_id" json:"tenant_id"`
	TaskID           string          `db:"task_id" json:"task_id"`
	Version          int32           `db:"version" json:"version"`
}

func (q *Queries) UpdateAgentStateOptimistic(ctx context.Context, arg UpdateAgentStateOptimisticParams) (AgentState, error) {
	row := q.db.QueryRow(ctx, updateAgentStateOptimistic,
		arg.CurrentPlan,
		arg.CurrentStep,
		arg.MemorySummary,
		arg.Constraints,
		arg.Artifacts,
		arg.LoopFingerprints,
		arg.TenantID,
		arg.TaskID,
		arg.Version,
	)
	var i AgentState
	err := row.Scan(
		&i.TaskID,
		&i.TenantID,
		&i.CurrentPlan,
		&i.CurrentStep,
		&i.MemorySummary,
		&i.Constraints,
		&i.Artifacts,
		&i.LoopFingerprints,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
